{
  "formatVersion": "1.1",
  "component": {
    "group": "org.dimdev",
    "module": "RiftLoader",
    "version": "2.0.0-20220326-1727",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "RiftLoader-2.0.0-20220326-1727.jar",
          "url": "RiftLoader-2.0.0-20220326-1727.jar",
          "size": 29826,
          "sha512": "33ed9371c7c25a210ee59f4d0a2b3af5f57f68414388476a2721412b01a7d49994e56f3636543a18a77950fd2c01f47f02006734b1390ca8e75b6e511ccb6e1d",
          "sha256": "971525cf2b491f04dcd96d6b2a0f67d244e43a6eaf4c826b6c19e293aa0bad3f",
          "sha1": "4baa5e8b6a13d82f80b8096d0f08a006255e1e90",
          "md5": "ea69ce5c955ce82af0172138747ae553"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "cn.enaium",
          "module": "launchwrapper",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "mixin",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "com.mojang",
          "module": "patchy",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "oshi-project",
          "module": "oshi-core",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "4.4.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "platform",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "com.ibm.icu",
          "module": "icu4j",
          "version": {
            "requires": "66.1"
          }
        },
        {
          "group": "com.mojang",
          "module": "javabridge",
          "version": {
            "requires": "1.0.22"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-all",
          "version": {
            "requires": "4.1.25.Final"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "21.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "net.java.jinput",
          "module": "jinput",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "net.java.jutils",
          "module": "jutils",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.mojang",
          "module": "brigadier",
          "version": {
            "requires": "1.0.17"
          }
        },
        {
          "group": "com.mojang",
          "module": "datafixerupper",
          "version": {
            "requires": "4.0.26"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "com.mojang",
          "module": "authlib",
          "version": {
            "requires": "2.1.28"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.3.3"
          }
        },
        {
          "group": "commons-logging",
          "module": "commons-logging",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpcore",
          "version": {
            "requires": "4.3.2"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-tinyfd",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.mojang",
          "module": "text2speech",
          "version": {
            "requires": "1.11.3"
          }
        },
        {
          "group": "ca.weblite",
          "module": "java-objc-bridge",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "RiftLoader-2.0.0-20220326-1727.jar",
          "url": "RiftLoader-2.0.0-20220326-1727.jar",
          "size": 29826,
          "sha512": "33ed9371c7c25a210ee59f4d0a2b3af5f57f68414388476a2721412b01a7d49994e56f3636543a18a77950fd2c01f47f02006734b1390ca8e75b6e511ccb6e1d",
          "sha256": "971525cf2b491f04dcd96d6b2a0f67d244e43a6eaf4c826b6c19e293aa0bad3f",
          "sha1": "4baa5e8b6a13d82f80b8096d0f08a006255e1e90",
          "md5": "ea69ce5c955ce82af0172138747ae553"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "RiftLoader-2.0.0-20220326-1727-sources.jar",
          "url": "RiftLoader-2.0.0-20220326-1727-sources.jar",
          "size": 14053,
          "sha512": "986ce493247bbc69ba71b9a341a51255130abd3dc731f2bd27d665c595f870da4433fe74e4ad9e6ccef33028c3d462ae396d2ce19bfbb197825dd3c9aa141fa9",
          "sha256": "534ea22c8327edd437ca064c661158016f87b65dfa85981f18be612662e6b6b0",
          "sha1": "ab3e153e65ce08c0ebd01111200832c4cd1bf763",
          "md5": "03357bd82928f3571f00b6bec60b1ed9"
        }
      ]
    }
  ]
}
